// Code generated by protoc-gen-go. DO NOT EDIT.
// source: abcitypes.proto

package abci

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckTxType int32

const (
	CheckTxType_NEW     CheckTxType = 0
	CheckTxType_RECHECK CheckTxType = 1
)

var CheckTxType_name = map[int32]string{
	0: "NEW",
	1: "RECHECK",
}

var CheckTxType_value = map[string]int32{
	"NEW":     0,
	"RECHECK": 1,
}

func (x CheckTxType) String() string {
	return proto.EnumName(CheckTxType_name, int32(x))
}

func (CheckTxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{0}
}

type ResponseOfferSnapshot_Result int32

const (
	ResponseOfferSnapshot_UNKNOWN       ResponseOfferSnapshot_Result = 0
	ResponseOfferSnapshot_ACCEPT        ResponseOfferSnapshot_Result = 1
	ResponseOfferSnapshot_ABORT         ResponseOfferSnapshot_Result = 2
	ResponseOfferSnapshot_REJECT        ResponseOfferSnapshot_Result = 3
	ResponseOfferSnapshot_REJECT_FORMAT ResponseOfferSnapshot_Result = 4
	ResponseOfferSnapshot_REJECT_SENDER ResponseOfferSnapshot_Result = 5
)

var ResponseOfferSnapshot_Result_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCEPT",
	2: "ABORT",
	3: "REJECT",
	4: "REJECT_FORMAT",
	5: "REJECT_SENDER",
}

var ResponseOfferSnapshot_Result_value = map[string]int32{
	"UNKNOWN":       0,
	"ACCEPT":        1,
	"ABORT":         2,
	"REJECT":        3,
	"REJECT_FORMAT": 4,
	"REJECT_SENDER": 5,
}

func (x ResponseOfferSnapshot_Result) String() string {
	return proto.EnumName(ResponseOfferSnapshot_Result_name, int32(x))
}

func (ResponseOfferSnapshot_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{23, 0}
}

type ResponseApplySnapshotChunk_Result int32

const (
	ResponseApplySnapshotChunk_UNKNOWN         ResponseApplySnapshotChunk_Result = 0
	ResponseApplySnapshotChunk_ACCEPT          ResponseApplySnapshotChunk_Result = 1
	ResponseApplySnapshotChunk_ABORT           ResponseApplySnapshotChunk_Result = 2
	ResponseApplySnapshotChunk_RETRY           ResponseApplySnapshotChunk_Result = 3
	ResponseApplySnapshotChunk_RETRY_SNAPSHOT  ResponseApplySnapshotChunk_Result = 4
	ResponseApplySnapshotChunk_REJECT_SNAPSHOT ResponseApplySnapshotChunk_Result = 5
)

var ResponseApplySnapshotChunk_Result_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCEPT",
	2: "ABORT",
	3: "RETRY",
	4: "RETRY_SNAPSHOT",
	5: "REJECT_SNAPSHOT",
}

var ResponseApplySnapshotChunk_Result_value = map[string]int32{
	"UNKNOWN":         0,
	"ACCEPT":          1,
	"ABORT":           2,
	"RETRY":           3,
	"RETRY_SNAPSHOT":  4,
	"REJECT_SNAPSHOT": 5,
}

func (x ResponseApplySnapshotChunk_Result) String() string {
	return proto.EnumName(ResponseApplySnapshotChunk_Result_name, int32(x))
}

func (ResponseApplySnapshotChunk_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{27, 0}
}

type RequestEcho struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEcho) Reset()         { *m = RequestEcho{} }
func (m *RequestEcho) String() string { return proto.CompactTextString(m) }
func (*RequestEcho) ProtoMessage()    {}
func (*RequestEcho) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{0}
}

func (m *RequestEcho) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEcho.Unmarshal(m, b)
}
func (m *RequestEcho) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEcho.Marshal(b, m, deterministic)
}
func (m *RequestEcho) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEcho.Merge(m, src)
}
func (m *RequestEcho) XXX_Size() int {
	return xxx_messageInfo_RequestEcho.Size(m)
}
func (m *RequestEcho) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEcho.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEcho proto.InternalMessageInfo

func (m *RequestEcho) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseEcho struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseEcho) Reset()         { *m = ResponseEcho{} }
func (m *ResponseEcho) String() string { return proto.CompactTextString(m) }
func (*ResponseEcho) ProtoMessage()    {}
func (*ResponseEcho) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{1}
}

func (m *ResponseEcho) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEcho.Unmarshal(m, b)
}
func (m *ResponseEcho) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEcho.Marshal(b, m, deterministic)
}
func (m *ResponseEcho) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEcho.Merge(m, src)
}
func (m *ResponseEcho) XXX_Size() int {
	return xxx_messageInfo_ResponseEcho.Size(m)
}
func (m *ResponseEcho) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEcho.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEcho proto.InternalMessageInfo

func (m *ResponseEcho) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RequestFlush struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFlush) Reset()         { *m = RequestFlush{} }
func (m *RequestFlush) String() string { return proto.CompactTextString(m) }
func (*RequestFlush) ProtoMessage()    {}
func (*RequestFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{2}
}

func (m *RequestFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFlush.Unmarshal(m, b)
}
func (m *RequestFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFlush.Marshal(b, m, deterministic)
}
func (m *RequestFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFlush.Merge(m, src)
}
func (m *RequestFlush) XXX_Size() int {
	return xxx_messageInfo_RequestFlush.Size(m)
}
func (m *RequestFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFlush.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFlush proto.InternalMessageInfo

type ResponseFlush struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseFlush) Reset()         { *m = ResponseFlush{} }
func (m *ResponseFlush) String() string { return proto.CompactTextString(m) }
func (*ResponseFlush) ProtoMessage()    {}
func (*ResponseFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{3}
}

func (m *ResponseFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFlush.Unmarshal(m, b)
}
func (m *ResponseFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFlush.Marshal(b, m, deterministic)
}
func (m *ResponseFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFlush.Merge(m, src)
}
func (m *ResponseFlush) XXX_Size() int {
	return xxx_messageInfo_ResponseFlush.Size(m)
}
func (m *ResponseFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFlush.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFlush proto.InternalMessageInfo

type RequestInfo struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BlockVersino         uint64   `protobuf:"varint,2,opt,name=block_versino,json=blockVersino,proto3" json:"block_versino,omitempty"`
	P2PVersion           uint64   `protobuf:"varint,3,opt,name=p2p_version,json=p2pVersion,proto3" json:"p2p_version,omitempty"`
	AbciVersion          string   `protobuf:"bytes,4,opt,name=abci_version,json=abciVersion,proto3" json:"abci_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{4}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RequestInfo) GetBlockVersino() uint64 {
	if m != nil {
		return m.BlockVersino
	}
	return 0
}

func (m *RequestInfo) GetP2PVersion() uint64 {
	if m != nil {
		return m.P2PVersion
	}
	return 0
}

func (m *RequestInfo) GetAbciVersion() string {
	if m != nil {
		return m.AbciVersion
	}
	return ""
}

type ResponseInfo struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	AppVersion           uint64   `protobuf:"varint,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	LastBlockHeight      int64    `protobuf:"varint,4,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	LastBlockAppHash     []byte   `protobuf:"bytes,5,opt,name=last_block_app_hash,json=lastBlockAppHash,proto3" json:"last_block_app_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInfo) Reset()         { *m = ResponseInfo{} }
func (m *ResponseInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseInfo) ProtoMessage()    {}
func (*ResponseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{5}
}

func (m *ResponseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInfo.Unmarshal(m, b)
}
func (m *ResponseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInfo.Marshal(b, m, deterministic)
}
func (m *ResponseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInfo.Merge(m, src)
}
func (m *ResponseInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseInfo.Size(m)
}
func (m *ResponseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInfo proto.InternalMessageInfo

func (m *ResponseInfo) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ResponseInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ResponseInfo) GetAppVersion() uint64 {
	if m != nil {
		return m.AppVersion
	}
	return 0
}

func (m *ResponseInfo) GetLastBlockHeight() int64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *ResponseInfo) GetLastBlockAppHash() []byte {
	if m != nil {
		return m.LastBlockAppHash
	}
	return nil
}

type RequestDeliverTx struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDeliverTx) Reset()         { *m = RequestDeliverTx{} }
func (m *RequestDeliverTx) String() string { return proto.CompactTextString(m) }
func (*RequestDeliverTx) ProtoMessage()    {}
func (*RequestDeliverTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{6}
}

func (m *RequestDeliverTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDeliverTx.Unmarshal(m, b)
}
func (m *RequestDeliverTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDeliverTx.Marshal(b, m, deterministic)
}
func (m *RequestDeliverTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDeliverTx.Merge(m, src)
}
func (m *RequestDeliverTx) XXX_Size() int {
	return xxx_messageInfo_RequestDeliverTx.Size(m)
}
func (m *RequestDeliverTx) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDeliverTx.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDeliverTx proto.InternalMessageInfo

func (m *RequestDeliverTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type ResponseDeliverTx struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	GasWanted            int64    `protobuf:"varint,5,opt,name=gas_wanted,proto3" json:"gas_wanted,omitempty"`
	GasUsed              int64    `protobuf:"varint,6,opt,name=gas_used,proto3" json:"gas_used,omitempty"`
	Events               []*Event `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	Codespace            string   `protobuf:"bytes,8,opt,name=codespace,proto3" json:"codespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseDeliverTx) Reset()         { *m = ResponseDeliverTx{} }
func (m *ResponseDeliverTx) String() string { return proto.CompactTextString(m) }
func (*ResponseDeliverTx) ProtoMessage()    {}
func (*ResponseDeliverTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{7}
}

func (m *ResponseDeliverTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDeliverTx.Unmarshal(m, b)
}
func (m *ResponseDeliverTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDeliverTx.Marshal(b, m, deterministic)
}
func (m *ResponseDeliverTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDeliverTx.Merge(m, src)
}
func (m *ResponseDeliverTx) XXX_Size() int {
	return xxx_messageInfo_ResponseDeliverTx.Size(m)
}
func (m *ResponseDeliverTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDeliverTx.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDeliverTx proto.InternalMessageInfo

func (m *ResponseDeliverTx) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseDeliverTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseDeliverTx) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseDeliverTx) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseDeliverTx) GetGasWanted() int64 {
	if m != nil {
		return m.GasWanted
	}
	return 0
}

func (m *ResponseDeliverTx) GetGasUsed() int64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *ResponseDeliverTx) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ResponseDeliverTx) GetCodespace() string {
	if m != nil {
		return m.Codespace
	}
	return ""
}

type RequestCheckTx struct {
	Tx                   []byte      `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Type                 CheckTxType `protobuf:"varint,2,opt,name=type,proto3,enum=CheckTxType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RequestCheckTx) Reset()         { *m = RequestCheckTx{} }
func (m *RequestCheckTx) String() string { return proto.CompactTextString(m) }
func (*RequestCheckTx) ProtoMessage()    {}
func (*RequestCheckTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{8}
}

func (m *RequestCheckTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCheckTx.Unmarshal(m, b)
}
func (m *RequestCheckTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCheckTx.Marshal(b, m, deterministic)
}
func (m *RequestCheckTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCheckTx.Merge(m, src)
}
func (m *RequestCheckTx) XXX_Size() int {
	return xxx_messageInfo_RequestCheckTx.Size(m)
}
func (m *RequestCheckTx) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCheckTx.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCheckTx proto.InternalMessageInfo

func (m *RequestCheckTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *RequestCheckTx) GetType() CheckTxType {
	if m != nil {
		return m.Type
	}
	return CheckTxType_NEW
}

type ResponseCheckTx struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	GasWanted            int64    `protobuf:"varint,5,opt,name=gas_wanted,proto3" json:"gas_wanted,omitempty"`
	GasUsed              int64    `protobuf:"varint,6,opt,name=gas_used,proto3" json:"gas_used,omitempty"`
	Events               []*Event `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	Codespace            string   `protobuf:"bytes,8,opt,name=codespace,proto3" json:"codespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCheckTx) Reset()         { *m = ResponseCheckTx{} }
func (m *ResponseCheckTx) String() string { return proto.CompactTextString(m) }
func (*ResponseCheckTx) ProtoMessage()    {}
func (*ResponseCheckTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{9}
}

func (m *ResponseCheckTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCheckTx.Unmarshal(m, b)
}
func (m *ResponseCheckTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCheckTx.Marshal(b, m, deterministic)
}
func (m *ResponseCheckTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCheckTx.Merge(m, src)
}
func (m *ResponseCheckTx) XXX_Size() int {
	return xxx_messageInfo_ResponseCheckTx.Size(m)
}
func (m *ResponseCheckTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCheckTx.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCheckTx proto.InternalMessageInfo

func (m *ResponseCheckTx) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCheckTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseCheckTx) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseCheckTx) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseCheckTx) GetGasWanted() int64 {
	if m != nil {
		return m.GasWanted
	}
	return 0
}

func (m *ResponseCheckTx) GetGasUsed() int64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *ResponseCheckTx) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ResponseCheckTx) GetCodespace() string {
	if m != nil {
		return m.Codespace
	}
	return ""
}

type RequestQuery struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Prove                bool     `protobuf:"varint,4,opt,name=prove,proto3" json:"prove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestQuery) Reset()         { *m = RequestQuery{} }
func (m *RequestQuery) String() string { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()    {}
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{10}
}

func (m *RequestQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestQuery.Unmarshal(m, b)
}
func (m *RequestQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestQuery.Marshal(b, m, deterministic)
}
func (m *RequestQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestQuery.Merge(m, src)
}
func (m *RequestQuery) XXX_Size() int {
	return xxx_messageInfo_RequestQuery.Size(m)
}
func (m *RequestQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RequestQuery proto.InternalMessageInfo

func (m *RequestQuery) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RequestQuery) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RequestQuery) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RequestQuery) GetProve() bool {
	if m != nil {
		return m.Prove
	}
	return false
}

type ResponseQuery struct {
	Code                 uint32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Log                  string    `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Info                 string    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Index                int64     `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Key                  []byte    `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte    `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	ProofOps             *ProofOps `protobuf:"bytes,7,opt,name=proof_ops,json=proofOps,proto3" json:"proof_ops,omitempty"`
	Height               int64     `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Codespace            string    `protobuf:"bytes,9,opt,name=codespace,proto3" json:"codespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseQuery) Reset()         { *m = ResponseQuery{} }
func (m *ResponseQuery) String() string { return proto.CompactTextString(m) }
func (*ResponseQuery) ProtoMessage()    {}
func (*ResponseQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{11}
}

func (m *ResponseQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseQuery.Unmarshal(m, b)
}
func (m *ResponseQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseQuery.Marshal(b, m, deterministic)
}
func (m *ResponseQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseQuery.Merge(m, src)
}
func (m *ResponseQuery) XXX_Size() int {
	return xxx_messageInfo_ResponseQuery.Size(m)
}
func (m *ResponseQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseQuery proto.InternalMessageInfo

func (m *ResponseQuery) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseQuery) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseQuery) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseQuery) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ResponseQuery) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ResponseQuery) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResponseQuery) GetProofOps() *ProofOps {
	if m != nil {
		return m.ProofOps
	}
	return nil
}

func (m *ResponseQuery) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ResponseQuery) GetCodespace() string {
	if m != nil {
		return m.Codespace
	}
	return ""
}

type RequestCommit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCommit) Reset()         { *m = RequestCommit{} }
func (m *RequestCommit) String() string { return proto.CompactTextString(m) }
func (*RequestCommit) ProtoMessage()    {}
func (*RequestCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{12}
}

func (m *RequestCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCommit.Unmarshal(m, b)
}
func (m *RequestCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCommit.Marshal(b, m, deterministic)
}
func (m *RequestCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCommit.Merge(m, src)
}
func (m *RequestCommit) XXX_Size() int {
	return xxx_messageInfo_RequestCommit.Size(m)
}
func (m *RequestCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCommit.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCommit proto.InternalMessageInfo

type ResponseCommit struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RetainHeight         int64    `protobuf:"varint,2,opt,name=retain_height,json=retainHeight,proto3" json:"retain_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCommit) Reset()         { *m = ResponseCommit{} }
func (m *ResponseCommit) String() string { return proto.CompactTextString(m) }
func (*ResponseCommit) ProtoMessage()    {}
func (*ResponseCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{13}
}

func (m *ResponseCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCommit.Unmarshal(m, b)
}
func (m *ResponseCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCommit.Marshal(b, m, deterministic)
}
func (m *ResponseCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCommit.Merge(m, src)
}
func (m *ResponseCommit) XXX_Size() int {
	return xxx_messageInfo_ResponseCommit.Size(m)
}
func (m *ResponseCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCommit.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCommit proto.InternalMessageInfo

func (m *ResponseCommit) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseCommit) GetRetainHeight() int64 {
	if m != nil {
		return m.RetainHeight
	}
	return 0
}

type RequestInitChain struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	ChainId              string               `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ConsensusParams      *ConsensusParams     `protobuf:"bytes,3,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params,omitempty"`
	Validators           []*ValidatorUpdate   `protobuf:"bytes,4,rep,name=validators,proto3" json:"validators,omitempty"`
	AppStateBytes        []byte               `protobuf:"bytes,5,opt,name=app_state_bytes,json=appStateBytes,proto3" json:"app_state_bytes,omitempty"`
	InitialHeight        int64                `protobuf:"varint,6,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestInitChain) Reset()         { *m = RequestInitChain{} }
func (m *RequestInitChain) String() string { return proto.CompactTextString(m) }
func (*RequestInitChain) ProtoMessage()    {}
func (*RequestInitChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{14}
}

func (m *RequestInitChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInitChain.Unmarshal(m, b)
}
func (m *RequestInitChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInitChain.Marshal(b, m, deterministic)
}
func (m *RequestInitChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInitChain.Merge(m, src)
}
func (m *RequestInitChain) XXX_Size() int {
	return xxx_messageInfo_RequestInitChain.Size(m)
}
func (m *RequestInitChain) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInitChain.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInitChain proto.InternalMessageInfo

func (m *RequestInitChain) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *RequestInitChain) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *RequestInitChain) GetConsensusParams() *ConsensusParams {
	if m != nil {
		return m.ConsensusParams
	}
	return nil
}

func (m *RequestInitChain) GetValidators() []*ValidatorUpdate {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *RequestInitChain) GetAppStateBytes() []byte {
	if m != nil {
		return m.AppStateBytes
	}
	return nil
}

func (m *RequestInitChain) GetInitialHeight() int64 {
	if m != nil {
		return m.InitialHeight
	}
	return 0
}

type ResponseInitChain struct {
	ConsensusParams      *ConsensusParams   `protobuf:"bytes,1,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params,omitempty"`
	Validators           []*ValidatorUpdate `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
	AppHash              []byte             `protobuf:"bytes,3,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ResponseInitChain) Reset()         { *m = ResponseInitChain{} }
func (m *ResponseInitChain) String() string { return proto.CompactTextString(m) }
func (*ResponseInitChain) ProtoMessage()    {}
func (*ResponseInitChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{15}
}

func (m *ResponseInitChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInitChain.Unmarshal(m, b)
}
func (m *ResponseInitChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInitChain.Marshal(b, m, deterministic)
}
func (m *ResponseInitChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInitChain.Merge(m, src)
}
func (m *ResponseInitChain) XXX_Size() int {
	return xxx_messageInfo_ResponseInitChain.Size(m)
}
func (m *ResponseInitChain) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInitChain.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInitChain proto.InternalMessageInfo

func (m *ResponseInitChain) GetConsensusParams() *ConsensusParams {
	if m != nil {
		return m.ConsensusParams
	}
	return nil
}

func (m *ResponseInitChain) GetValidators() []*ValidatorUpdate {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *ResponseInitChain) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

type RequestBeginBlock struct {
	Hash                 []byte          `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header               *Header         `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	LastCommitInfo       *LastCommitInfo `protobuf:"bytes,3,opt,name=last_commit_info,json=lastCommitInfo,proto3" json:"last_commit_info,omitempty"`
	ByzantineValidators  []*Evidence     `protobuf:"bytes,4,rep,name=byzantine_validators,json=byzantineValidators,proto3" json:"byzantine_validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RequestBeginBlock) Reset()         { *m = RequestBeginBlock{} }
func (m *RequestBeginBlock) String() string { return proto.CompactTextString(m) }
func (*RequestBeginBlock) ProtoMessage()    {}
func (*RequestBeginBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{16}
}

func (m *RequestBeginBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBeginBlock.Unmarshal(m, b)
}
func (m *RequestBeginBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBeginBlock.Marshal(b, m, deterministic)
}
func (m *RequestBeginBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBeginBlock.Merge(m, src)
}
func (m *RequestBeginBlock) XXX_Size() int {
	return xxx_messageInfo_RequestBeginBlock.Size(m)
}
func (m *RequestBeginBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBeginBlock.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBeginBlock proto.InternalMessageInfo

func (m *RequestBeginBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RequestBeginBlock) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RequestBeginBlock) GetLastCommitInfo() *LastCommitInfo {
	if m != nil {
		return m.LastCommitInfo
	}
	return nil
}

func (m *RequestBeginBlock) GetByzantineValidators() []*Evidence {
	if m != nil {
		return m.ByzantineValidators
	}
	return nil
}

type ResponseBeginBlock struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseBeginBlock) Reset()         { *m = ResponseBeginBlock{} }
func (m *ResponseBeginBlock) String() string { return proto.CompactTextString(m) }
func (*ResponseBeginBlock) ProtoMessage()    {}
func (*ResponseBeginBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{17}
}

func (m *ResponseBeginBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBeginBlock.Unmarshal(m, b)
}
func (m *ResponseBeginBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBeginBlock.Marshal(b, m, deterministic)
}
func (m *ResponseBeginBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBeginBlock.Merge(m, src)
}
func (m *ResponseBeginBlock) XXX_Size() int {
	return xxx_messageInfo_ResponseBeginBlock.Size(m)
}
func (m *ResponseBeginBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBeginBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBeginBlock proto.InternalMessageInfo

func (m *ResponseBeginBlock) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type RequestEndBlock struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEndBlock) Reset()         { *m = RequestEndBlock{} }
func (m *RequestEndBlock) String() string { return proto.CompactTextString(m) }
func (*RequestEndBlock) ProtoMessage()    {}
func (*RequestEndBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{18}
}

func (m *RequestEndBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEndBlock.Unmarshal(m, b)
}
func (m *RequestEndBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEndBlock.Marshal(b, m, deterministic)
}
func (m *RequestEndBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEndBlock.Merge(m, src)
}
func (m *RequestEndBlock) XXX_Size() int {
	return xxx_messageInfo_RequestEndBlock.Size(m)
}
func (m *RequestEndBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEndBlock.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEndBlock proto.InternalMessageInfo

func (m *RequestEndBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ResponseEndBlock struct {
	ValidatorUpdates      []*ValidatorUpdate `protobuf:"bytes,1,rep,name=validator_updates,json=validatorUpdates,proto3" json:"validator_updates,omitempty"`
	ConsensusParamUpdates *ConsensusParams   `protobuf:"bytes,2,opt,name=consensus_param_updates,json=consensusParamUpdates,proto3" json:"consensus_param_updates,omitempty"`
	Events                []*Event           `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}           `json:"-"`
	XXX_unrecognized      []byte             `json:"-"`
	XXX_sizecache         int32              `json:"-"`
}

func (m *ResponseEndBlock) Reset()         { *m = ResponseEndBlock{} }
func (m *ResponseEndBlock) String() string { return proto.CompactTextString(m) }
func (*ResponseEndBlock) ProtoMessage()    {}
func (*ResponseEndBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{19}
}

func (m *ResponseEndBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEndBlock.Unmarshal(m, b)
}
func (m *ResponseEndBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEndBlock.Marshal(b, m, deterministic)
}
func (m *ResponseEndBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEndBlock.Merge(m, src)
}
func (m *ResponseEndBlock) XXX_Size() int {
	return xxx_messageInfo_ResponseEndBlock.Size(m)
}
func (m *ResponseEndBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEndBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEndBlock proto.InternalMessageInfo

func (m *ResponseEndBlock) GetValidatorUpdates() []*ValidatorUpdate {
	if m != nil {
		return m.ValidatorUpdates
	}
	return nil
}

func (m *ResponseEndBlock) GetConsensusParamUpdates() *ConsensusParams {
	if m != nil {
		return m.ConsensusParamUpdates
	}
	return nil
}

func (m *ResponseEndBlock) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type RequestListSnapshots struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestListSnapshots) Reset()         { *m = RequestListSnapshots{} }
func (m *RequestListSnapshots) String() string { return proto.CompactTextString(m) }
func (*RequestListSnapshots) ProtoMessage()    {}
func (*RequestListSnapshots) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{20}
}

func (m *RequestListSnapshots) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestListSnapshots.Unmarshal(m, b)
}
func (m *RequestListSnapshots) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestListSnapshots.Marshal(b, m, deterministic)
}
func (m *RequestListSnapshots) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestListSnapshots.Merge(m, src)
}
func (m *RequestListSnapshots) XXX_Size() int {
	return xxx_messageInfo_RequestListSnapshots.Size(m)
}
func (m *RequestListSnapshots) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestListSnapshots.DiscardUnknown(m)
}

var xxx_messageInfo_RequestListSnapshots proto.InternalMessageInfo

type ResponseListSnapshots struct {
	Snapshots            []*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseListSnapshots) Reset()         { *m = ResponseListSnapshots{} }
func (m *ResponseListSnapshots) String() string { return proto.CompactTextString(m) }
func (*ResponseListSnapshots) ProtoMessage()    {}
func (*ResponseListSnapshots) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{21}
}

func (m *ResponseListSnapshots) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseListSnapshots.Unmarshal(m, b)
}
func (m *ResponseListSnapshots) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseListSnapshots.Marshal(b, m, deterministic)
}
func (m *ResponseListSnapshots) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseListSnapshots.Merge(m, src)
}
func (m *ResponseListSnapshots) XXX_Size() int {
	return xxx_messageInfo_ResponseListSnapshots.Size(m)
}
func (m *ResponseListSnapshots) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseListSnapshots.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseListSnapshots proto.InternalMessageInfo

func (m *ResponseListSnapshots) GetSnapshots() []*Snapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type RequestOfferSnapshot struct {
	Snapshot             *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	AppHash              []byte    `protobuf:"bytes,2,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RequestOfferSnapshot) Reset()         { *m = RequestOfferSnapshot{} }
func (m *RequestOfferSnapshot) String() string { return proto.CompactTextString(m) }
func (*RequestOfferSnapshot) ProtoMessage()    {}
func (*RequestOfferSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{22}
}

func (m *RequestOfferSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOfferSnapshot.Unmarshal(m, b)
}
func (m *RequestOfferSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOfferSnapshot.Marshal(b, m, deterministic)
}
func (m *RequestOfferSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOfferSnapshot.Merge(m, src)
}
func (m *RequestOfferSnapshot) XXX_Size() int {
	return xxx_messageInfo_RequestOfferSnapshot.Size(m)
}
func (m *RequestOfferSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOfferSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOfferSnapshot proto.InternalMessageInfo

func (m *RequestOfferSnapshot) GetSnapshot() *Snapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *RequestOfferSnapshot) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

type ResponseOfferSnapshot struct {
	Result               ResponseOfferSnapshot_Result `protobuf:"varint,1,opt,name=result,proto3,enum=ResponseOfferSnapshot_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ResponseOfferSnapshot) Reset()         { *m = ResponseOfferSnapshot{} }
func (m *ResponseOfferSnapshot) String() string { return proto.CompactTextString(m) }
func (*ResponseOfferSnapshot) ProtoMessage()    {}
func (*ResponseOfferSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{23}
}

func (m *ResponseOfferSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOfferSnapshot.Unmarshal(m, b)
}
func (m *ResponseOfferSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOfferSnapshot.Marshal(b, m, deterministic)
}
func (m *ResponseOfferSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOfferSnapshot.Merge(m, src)
}
func (m *ResponseOfferSnapshot) XXX_Size() int {
	return xxx_messageInfo_ResponseOfferSnapshot.Size(m)
}
func (m *ResponseOfferSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOfferSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOfferSnapshot proto.InternalMessageInfo

func (m *ResponseOfferSnapshot) GetResult() ResponseOfferSnapshot_Result {
	if m != nil {
		return m.Result
	}
	return ResponseOfferSnapshot_UNKNOWN
}

type RequestLoadSnapshotChunk struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Format               uint32   `protobuf:"varint,2,opt,name=format,proto3" json:"format,omitempty"`
	Chunk                uint32   `protobuf:"varint,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLoadSnapshotChunk) Reset()         { *m = RequestLoadSnapshotChunk{} }
func (m *RequestLoadSnapshotChunk) String() string { return proto.CompactTextString(m) }
func (*RequestLoadSnapshotChunk) ProtoMessage()    {}
func (*RequestLoadSnapshotChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{24}
}

func (m *RequestLoadSnapshotChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLoadSnapshotChunk.Unmarshal(m, b)
}
func (m *RequestLoadSnapshotChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLoadSnapshotChunk.Marshal(b, m, deterministic)
}
func (m *RequestLoadSnapshotChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLoadSnapshotChunk.Merge(m, src)
}
func (m *RequestLoadSnapshotChunk) XXX_Size() int {
	return xxx_messageInfo_RequestLoadSnapshotChunk.Size(m)
}
func (m *RequestLoadSnapshotChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLoadSnapshotChunk.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLoadSnapshotChunk proto.InternalMessageInfo

func (m *RequestLoadSnapshotChunk) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RequestLoadSnapshotChunk) GetFormat() uint32 {
	if m != nil {
		return m.Format
	}
	return 0
}

func (m *RequestLoadSnapshotChunk) GetChunk() uint32 {
	if m != nil {
		return m.Chunk
	}
	return 0
}

type ResponseLoadSnapshotChunk struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseLoadSnapshotChunk) Reset()         { *m = ResponseLoadSnapshotChunk{} }
func (m *ResponseLoadSnapshotChunk) String() string { return proto.CompactTextString(m) }
func (*ResponseLoadSnapshotChunk) ProtoMessage()    {}
func (*ResponseLoadSnapshotChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{25}
}

func (m *ResponseLoadSnapshotChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLoadSnapshotChunk.Unmarshal(m, b)
}
func (m *ResponseLoadSnapshotChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLoadSnapshotChunk.Marshal(b, m, deterministic)
}
func (m *ResponseLoadSnapshotChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLoadSnapshotChunk.Merge(m, src)
}
func (m *ResponseLoadSnapshotChunk) XXX_Size() int {
	return xxx_messageInfo_ResponseLoadSnapshotChunk.Size(m)
}
func (m *ResponseLoadSnapshotChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLoadSnapshotChunk.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLoadSnapshotChunk proto.InternalMessageInfo

func (m *ResponseLoadSnapshotChunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type RequestApplySnapshotChunk struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Chunk                []byte   `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Sender               string   `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestApplySnapshotChunk) Reset()         { *m = RequestApplySnapshotChunk{} }
func (m *RequestApplySnapshotChunk) String() string { return proto.CompactTextString(m) }
func (*RequestApplySnapshotChunk) ProtoMessage()    {}
func (*RequestApplySnapshotChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{26}
}

func (m *RequestApplySnapshotChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestApplySnapshotChunk.Unmarshal(m, b)
}
func (m *RequestApplySnapshotChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestApplySnapshotChunk.Marshal(b, m, deterministic)
}
func (m *RequestApplySnapshotChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestApplySnapshotChunk.Merge(m, src)
}
func (m *RequestApplySnapshotChunk) XXX_Size() int {
	return xxx_messageInfo_RequestApplySnapshotChunk.Size(m)
}
func (m *RequestApplySnapshotChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestApplySnapshotChunk.DiscardUnknown(m)
}

var xxx_messageInfo_RequestApplySnapshotChunk proto.InternalMessageInfo

func (m *RequestApplySnapshotChunk) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RequestApplySnapshotChunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (m *RequestApplySnapshotChunk) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type ResponseApplySnapshotChunk struct {
	Result               ResponseApplySnapshotChunk_Result `protobuf:"varint,1,opt,name=result,proto3,enum=ResponseApplySnapshotChunk_Result" json:"result,omitempty"`
	RefetchChunks        []uint32                          `protobuf:"varint,2,rep,packed,name=refetch_chunks,json=refetchChunks,proto3" json:"refetch_chunks,omitempty"`
	RejectSenders        []string                          `protobuf:"bytes,3,rep,name=reject_senders,json=rejectSenders,proto3" json:"reject_senders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ResponseApplySnapshotChunk) Reset()         { *m = ResponseApplySnapshotChunk{} }
func (m *ResponseApplySnapshotChunk) String() string { return proto.CompactTextString(m) }
func (*ResponseApplySnapshotChunk) ProtoMessage()    {}
func (*ResponseApplySnapshotChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae10df23e9a3850, []int{27}
}

func (m *ResponseApplySnapshotChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseApplySnapshotChunk.Unmarshal(m, b)
}
func (m *ResponseApplySnapshotChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseApplySnapshotChunk.Marshal(b, m, deterministic)
}
func (m *ResponseApplySnapshotChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseApplySnapshotChunk.Merge(m, src)
}
func (m *ResponseApplySnapshotChunk) XXX_Size() int {
	return xxx_messageInfo_ResponseApplySnapshotChunk.Size(m)
}
func (m *ResponseApplySnapshotChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseApplySnapshotChunk.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseApplySnapshotChunk proto.InternalMessageInfo

func (m *ResponseApplySnapshotChunk) GetResult() ResponseApplySnapshotChunk_Result {
	if m != nil {
		return m.Result
	}
	return ResponseApplySnapshotChunk_UNKNOWN
}

func (m *ResponseApplySnapshotChunk) GetRefetchChunks() []uint32 {
	if m != nil {
		return m.RefetchChunks
	}
	return nil
}

func (m *ResponseApplySnapshotChunk) GetRejectSenders() []string {
	if m != nil {
		return m.RejectSenders
	}
	return nil
}

func init() {
	proto.RegisterEnum("CheckTxType", CheckTxType_name, CheckTxType_value)
	proto.RegisterEnum("ResponseOfferSnapshot_Result", ResponseOfferSnapshot_Result_name, ResponseOfferSnapshot_Result_value)
	proto.RegisterEnum("ResponseApplySnapshotChunk_Result", ResponseApplySnapshotChunk_Result_name, ResponseApplySnapshotChunk_Result_value)
	proto.RegisterType((*RequestEcho)(nil), "RequestEcho")
	proto.RegisterType((*ResponseEcho)(nil), "ResponseEcho")
	proto.RegisterType((*RequestFlush)(nil), "RequestFlush")
	proto.RegisterType((*ResponseFlush)(nil), "ResponseFlush")
	proto.RegisterType((*RequestInfo)(nil), "RequestInfo")
	proto.RegisterType((*ResponseInfo)(nil), "ResponseInfo")
	proto.RegisterType((*RequestDeliverTx)(nil), "RequestDeliverTx")
	proto.RegisterType((*ResponseDeliverTx)(nil), "ResponseDeliverTx")
	proto.RegisterType((*RequestCheckTx)(nil), "RequestCheckTx")
	proto.RegisterType((*ResponseCheckTx)(nil), "ResponseCheckTx")
	proto.RegisterType((*RequestQuery)(nil), "RequestQuery")
	proto.RegisterType((*ResponseQuery)(nil), "ResponseQuery")
	proto.RegisterType((*RequestCommit)(nil), "RequestCommit")
	proto.RegisterType((*ResponseCommit)(nil), "ResponseCommit")
	proto.RegisterType((*RequestInitChain)(nil), "RequestInitChain")
	proto.RegisterType((*ResponseInitChain)(nil), "ResponseInitChain")
	proto.RegisterType((*RequestBeginBlock)(nil), "RequestBeginBlock")
	proto.RegisterType((*ResponseBeginBlock)(nil), "ResponseBeginBlock")
	proto.RegisterType((*RequestEndBlock)(nil), "RequestEndBlock")
	proto.RegisterType((*ResponseEndBlock)(nil), "ResponseEndBlock")
	proto.RegisterType((*RequestListSnapshots)(nil), "RequestListSnapshots")
	proto.RegisterType((*ResponseListSnapshots)(nil), "ResponseListSnapshots")
	proto.RegisterType((*RequestOfferSnapshot)(nil), "RequestOfferSnapshot")
	proto.RegisterType((*ResponseOfferSnapshot)(nil), "ResponseOfferSnapshot")
	proto.RegisterType((*RequestLoadSnapshotChunk)(nil), "RequestLoadSnapshotChunk")
	proto.RegisterType((*ResponseLoadSnapshotChunk)(nil), "ResponseLoadSnapshotChunk")
	proto.RegisterType((*RequestApplySnapshotChunk)(nil), "RequestApplySnapshotChunk")
	proto.RegisterType((*ResponseApplySnapshotChunk)(nil), "ResponseApplySnapshotChunk")
}

func init() { proto.RegisterFile("abcitypes.proto", fileDescriptor_2ae10df23e9a3850) }

var fileDescriptor_2ae10df23e9a3850 = []byte{
	// 1698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x57, 0x4f, 0x73, 0x23, 0x47,
	0x15, 0xdf, 0x19, 0xfd, 0xb1, 0xf4, 0xf4, 0x6f, 0xdc, 0xf6, 0x1a, 0xed, 0x90, 0x60, 0x33, 0x29,
	0x36, 0xde, 0x54, 0x76, 0x5c, 0x28, 0xa4, 0x0a, 0x38, 0xa4, 0xca, 0x52, 0x94, 0xb2, 0x93, 0x5d,
	0xdb, 0x8c, 0xbd, 0x9b, 0x02, 0xaa, 0x98, 0xb4, 0x46, 0x2d, 0x69, 0x58, 0x69, 0x66, 0x50, 0xb7,
	0xbc, 0x16, 0x27, 0x8a, 0x13, 0x95, 0x53, 0xbe, 0x40, 0xbe, 0x02, 0x67, 0x2e, 0x1c, 0xa9, 0xe2,
	0x53, 0x84, 0x3b, 0x17, 0xaa, 0x38, 0x72, 0xa2, 0xfa, 0xdf, 0x68, 0x46, 0x92, 0x21, 0x10, 0x6e,
	0xdc, 0xba, 0x5f, 0xff, 0xde, 0xeb, 0xf7, 0x7e, 0xfd, 0xfa, 0xbd, 0x6e, 0x68, 0xe1, 0x41, 0x10,
	0xb2, 0x65, 0x42, 0xa8, 0x9b, 0xcc, 0x63, 0x16, 0xdb, 0xfb, 0xe3, 0x78, 0x1c, 0x8b, 0xe1, 0x09,
	0x1f, 0x29, 0xe9, 0xe1, 0x38, 0x8e, 0xc7, 0x53, 0x72, 0x22, 0x66, 0x83, 0xc5, 0xe8, 0x84, 0x85,
	0x33, 0x42, 0x19, 0x9e, 0x25, 0x0a, 0xb0, 0x37, 0x23, 0x94, 0xe2, 0x31, 0xf1, 0x33, 0xb6, 0x9c,
	0xb7, 0xa1, 0xe6, 0x91, 0x5f, 0x2d, 0x08, 0x65, 0xfd, 0x60, 0x12, 0xa3, 0x36, 0xec, 0x28, 0x54,
	0xdb, 0x38, 0x32, 0x8e, 0xab, 0x9e, 0x9e, 0x3a, 0xc7, 0x50, 0xf7, 0x08, 0x4d, 0xe2, 0x88, 0x92,
	0x7f, 0x83, 0x6c, 0x72, 0xa4, 0x30, 0xf9, 0xd1, 0x74, 0x41, 0x27, 0x4e, 0x0b, 0x1a, 0x5a, 0x53,
	0x0a, 0xbe, 0x30, 0xd2, 0x4d, 0xcf, 0xa3, 0x91, 0x30, 0x75, 0x4b, 0xe6, 0x34, 0x8c, 0x23, 0x6d,
	0x4a, 0x4d, 0xd1, 0x5b, 0xd0, 0x18, 0x4c, 0xe3, 0xe0, 0x95, 0x2f, 0x04, 0x51, 0xdc, 0x36, 0x8f,
	0x8c, 0xe3, 0xa2, 0x57, 0x17, 0xc2, 0x97, 0x52, 0x86, 0x0e, 0xa1, 0x96, 0x74, 0x12, 0x5f, 0x9b,
	0x28, 0x08, 0x08, 0x24, 0x9d, 0xe4, 0xa5, 0xb2, 0xf2, 0x5d, 0xa8, 0x73, 0x0a, 0x53, 0x44, 0x51,
	0x6c, 0x52, 0xe3, 0x32, 0x05, 0x71, 0xfe, 0x60, 0xac, 0xc2, 0x13, 0x3e, 0x21, 0x28, 0x0e, 0x31,
	0xc3, 0xca, 0x21, 0x31, 0xce, 0xfa, 0x69, 0xe6, 0xfd, 0x3c, 0x84, 0x1a, 0x4e, 0x36, 0x5c, 0xc0,
	0x49, 0xea, 0xc2, 0x3b, 0xb0, 0x3b, 0xc5, 0x94, 0xf9, 0x32, 0x9a, 0x09, 0x09, 0xc7, 0x13, 0x26,
	0xfc, 0x28, 0x78, 0x2d, 0xbe, 0xd0, 0xe5, 0xf2, 0x33, 0x21, 0x46, 0x4f, 0x61, 0x2f, 0x83, 0xe5,
	0x76, 0x27, 0x98, 0x4e, 0xda, 0xa5, 0x23, 0xe3, 0xb8, 0xee, 0x59, 0x29, 0xfa, 0x34, 0x49, 0xce,
	0x30, 0x9d, 0x38, 0x0e, 0x58, 0x8a, 0xcc, 0x0f, 0xc9, 0x34, 0xbc, 0x25, 0xf3, 0x9b, 0x3b, 0xd4,
	0x04, 0x93, 0xdd, 0x09, 0xdf, 0xeb, 0x9e, 0xc9, 0xee, 0x9c, 0xdf, 0x9a, 0xb0, 0xab, 0xc3, 0x5b,
	0xa1, 0x10, 0x14, 0x83, 0x78, 0x28, 0xcf, 0xaf, 0xe1, 0x89, 0x71, 0x1a, 0xb7, 0x29, 0x74, 0x65,
	0xdc, 0x16, 0x14, 0xa6, 0xf1, 0x58, 0x44, 0x55, 0xf5, 0xf8, 0x90, 0xa3, 0xc2, 0x68, 0x14, 0x2b,
	0x26, 0xc5, 0x18, 0x7d, 0x07, 0x60, 0x8c, 0xa9, 0xff, 0x1a, 0x47, 0x8c, 0x0c, 0x85, 0xb7, 0x05,
	0x2f, 0x23, 0x41, 0x36, 0x54, 0xf8, 0x6c, 0x41, 0xc9, 0xb0, 0x5d, 0x16, 0xab, 0xe9, 0x1c, 0xf5,
	0xa1, 0x4c, 0x6e, 0x49, 0xc4, 0x68, 0x7b, 0xe7, 0xa8, 0x70, 0x5c, 0xeb, 0xec, 0xb9, 0x2a, 0x99,
	0x64, 0xaa, 0xf6, 0xf9, 0x5a, 0xb7, 0xfd, 0xe7, 0xaf, 0x0e, 0x1f, 0xfc, 0xf5, 0xab, 0x43, 0x4b,
	0x42, 0xdf, 0x8d, 0x67, 0x21, 0x23, 0xb3, 0x84, 0x2d, 0x3d, 0xa5, 0x8c, 0xde, 0x80, 0x2a, 0x0f,
	0x82, 0x26, 0x38, 0x20, 0xed, 0x8a, 0xf0, 0x6d, 0x25, 0x70, 0xba, 0xd0, 0x54, 0x44, 0xf5, 0x26,
	0x24, 0x78, 0xb5, 0x49, 0x13, 0x3a, 0x82, 0x22, 0xdf, 0x50, 0x04, 0xdf, 0xec, 0xd4, 0x5d, 0x85,
	0xbb, 0x59, 0x26, 0xc4, 0x13, 0x2b, 0xce, 0x6f, 0x4c, 0x68, 0x69, 0x22, 0xb5, 0x95, 0xff, 0x33,
	0x1a, 0x87, 0xe9, 0xf5, 0xfe, 0xc9, 0x82, 0xcc, 0x97, 0xb9, 0x9b, 0xa2, 0x43, 0x45, 0x50, 0x4c,
	0x30, 0x9b, 0xa8, 0x6b, 0x22, 0xc6, 0xe8, 0x00, 0xca, 0x2a, 0xef, 0x0b, 0xc2, 0x6d, 0x35, 0x43,
	0xfb, 0x50, 0x4a, 0xe6, 0xf1, 0x2d, 0x11, 0x2c, 0x54, 0x3c, 0x39, 0x71, 0xfe, 0x6e, 0xac, 0xaa,
	0x46, 0xba, 0xcf, 0x06, 0xcd, 0x8a, 0x52, 0x73, 0x93, 0xd2, 0x42, 0x86, 0xd2, 0x7d, 0x28, 0x85,
	0xd1, 0x90, 0xdc, 0xa9, 0x0b, 0x27, 0x27, 0x5c, 0xf7, 0x15, 0x59, 0xaa, 0x6b, 0xc5, 0x87, 0x1c,
	0x77, 0x8b, 0xa7, 0x0b, 0x22, 0x78, 0xad, 0x7b, 0x72, 0x82, 0xde, 0x83, 0x6a, 0x32, 0x8f, 0xe3,
	0x91, 0x1f, 0x27, 0x9c, 0x57, 0xe3, 0xb8, 0xd6, 0x39, 0xc8, 0xf3, 0x7a, 0xc5, 0x97, 0x2f, 0x13,
	0xea, 0x55, 0x12, 0x35, 0xca, 0x04, 0x5b, 0xc9, 0x05, 0x9b, 0xa3, 0xb6, 0xba, 0x4e, 0xad, 0xa8,
	0x94, 0x32, 0x43, 0xe3, 0xd9, 0x2c, 0x64, 0xce, 0x39, 0x4f, 0x59, 0x95, 0x6d, 0x42, 0xb2, 0x95,
	0xed, 0xb7, 0xa0, 0x31, 0x27, 0x0c, 0x87, 0x91, 0x2e, 0x2c, 0xa6, 0xd8, 0xb3, 0x2e, 0x85, 0xb2,
	0xaa, 0x38, 0x7f, 0x32, 0xd3, 0x3a, 0x71, 0x1e, 0x85, 0xac, 0x37, 0xc1, 0x61, 0x84, 0x7e, 0x08,
	0x45, 0xde, 0x25, 0x84, 0xb5, 0x5a, 0xc7, 0x76, 0x65, 0x0b, 0x71, 0x75, 0x0b, 0x71, 0x6f, 0x74,
	0x0b, 0xe9, 0x56, 0x78, 0xd6, 0x7c, 0xf1, 0x97, 0x43, 0xc3, 0x13, 0x1a, 0xe8, 0x11, 0x54, 0x02,
	0x6e, 0xc2, 0x0f, 0x87, 0xba, 0x18, 0x8a, 0xf9, 0xf9, 0x10, 0x9d, 0x81, 0x15, 0x70, 0x8f, 0x23,
	0xba, 0xa0, 0x7e, 0x82, 0xe7, 0x78, 0x46, 0xc5, 0x71, 0xd4, 0x3a, 0x6f, 0xe6, 0x79, 0xeb, 0x69,
	0xd4, 0x95, 0x00, 0x79, 0xad, 0x20, 0x2f, 0x40, 0x3d, 0x80, 0x5b, 0x3c, 0x0d, 0x87, 0x98, 0xc5,
	0x73, 0xda, 0x2e, 0x8a, 0x9c, 0x5e, 0xb3, 0xf1, 0x52, 0xaf, 0xbf, 0x48, 0x86, 0x98, 0x91, 0x6e,
	0x91, 0xfb, 0xe9, 0x65, 0xd4, 0xd0, 0x63, 0x68, 0xf1, 0x1a, 0x4a, 0x19, 0x66, 0xc4, 0x1f, 0x2c,
	0x19, 0xa1, 0xea, 0xcc, 0x1b, 0x38, 0x49, 0xae, 0xb9, 0xb4, 0xcb, 0x85, 0xe8, 0x7b, 0xd0, 0x0c,
	0xa3, 0x90, 0x85, 0x78, 0xaa, 0x69, 0x94, 0xd7, 0xab, 0xa1, 0xa4, 0x8a, 0xc7, 0x3f, 0x1a, 0xab,
	0x52, 0xba, 0x22, 0x72, 0x5b, 0xcc, 0xc6, 0xff, 0x20, 0x66, 0xf3, 0xbf, 0x8b, 0xf9, 0x11, 0x54,
	0xd2, 0xbe, 0x51, 0x10, 0xc1, 0xee, 0x60, 0xd5, 0x2e, 0xfe, 0x21, 0xfc, 0x17, 0x79, 0xd0, 0x25,
	0xe3, 0x30, 0x12, 0xbd, 0x84, 0xa7, 0x95, 0x00, 0xab, 0xb4, 0xe2, 0x63, 0xd4, 0xe1, 0x39, 0x8c,
	0x87, 0x64, 0x2e, 0x0e, 0xb8, 0xd6, 0xd9, 0xcf, 0x7b, 0x71, 0x26, 0xd6, 0xd4, 0xe6, 0x0a, 0x89,
	0x9e, 0x81, 0x68, 0x50, 0x7e, 0x20, 0xb2, 0xd5, 0x4f, 0xaf, 0x62, 0xad, 0xf3, 0x46, 0x5e, 0xfb,
	0x19, 0xd6, 0x49, 0xce, 0xdb, 0xad, 0xb2, 0xd2, 0x9c, 0xe6, 0xa4, 0xe8, 0x12, 0xf6, 0x07, 0xcb,
	0x5f, 0xe3, 0x88, 0x85, 0x11, 0xf1, 0x37, 0x32, 0xe1, 0x60, 0xbd, 0xba, 0x85, 0x43, 0x12, 0x05,
	0x9a, 0x8e, 0xbd, 0x54, 0x33, 0xa5, 0x8b, 0x3a, 0x3f, 0x07, 0xa4, 0xcf, 0x2e, 0x13, 0xfc, 0xaa,
	0x6c, 0x1a, 0xdf, 0xa0, 0x6c, 0x3a, 0x4f, 0x78, 0x6b, 0x90, 0x4f, 0xa9, 0x68, 0x28, 0x2d, 0xaf,
	0xca, 0x80, 0x91, 0x2d, 0x03, 0xbc, 0x1f, 0x5b, 0xe9, 0x6b, 0x4a, 0x83, 0xaf, 0x60, 0x37, 0x8d,
	0xd1, 0x5f, 0x88, 0xa3, 0xd5, 0x1e, 0x7d, 0xad, 0x04, 0xb0, 0x6e, 0xf3, 0x62, 0x8a, 0x5e, 0xc0,
	0xb7, 0xd6, 0xb2, 0x32, 0xb5, 0x6b, 0x7e, 0x9d, 0xe4, 0x7c, 0x98, 0x4f, 0x4e, 0x6d, 0x76, 0xc5,
	0x57, 0xe1, 0x9b, 0xf0, 0x75, 0x00, 0xfb, 0x8a, 0xaf, 0x67, 0x21, 0x65, 0xd7, 0x11, 0x4e, 0xe8,
	0x24, 0x66, 0xd4, 0x79, 0x0e, 0x0f, 0x35, 0x37, 0xb9, 0x05, 0xf4, 0x03, 0xa8, 0x52, 0x3d, 0x51,
	0xc4, 0xac, 0xe5, 0x80, 0xc6, 0x7a, 0x2b, 0xa0, 0x43, 0xd2, 0x6d, 0x2e, 0x47, 0x23, 0x32, 0xd7,
	0x10, 0xd4, 0x81, 0x8a, 0x06, 0xa9, 0xab, 0x7a, 0x9f, 0xb1, 0x14, 0x97, 0xbb, 0x57, 0x66, 0xfe,
	0x5e, 0xfd, 0xde, 0x58, 0xb9, 0x9d, 0xdf, 0xe8, 0x7d, 0x28, 0xcf, 0x09, 0x5d, 0x4c, 0xe5, 0x36,
	0xcd, 0xce, 0x9b, 0xee, 0x56, 0x1c, 0x97, 0x2e, 0xa6, 0xcc, 0x53, 0x60, 0xe7, 0x17, 0x50, 0x96,
	0x12, 0x54, 0x83, 0x9d, 0x17, 0x17, 0x9f, 0x5c, 0x5c, 0x7e, 0x7a, 0x61, 0x3d, 0x40, 0x00, 0xe5,
	0xd3, 0x5e, 0xaf, 0x7f, 0x75, 0x63, 0x19, 0xa8, 0x0a, 0xa5, 0xd3, 0xee, 0xa5, 0x77, 0x63, 0x99,
	0x5c, 0xec, 0xf5, 0x3f, 0xee, 0xf7, 0x6e, 0xac, 0x02, 0xda, 0x85, 0x86, 0x1c, 0xfb, 0x1f, 0x5d,
	0x7a, 0xcf, 0x4f, 0x6f, 0xac, 0x62, 0x46, 0x74, 0xdd, 0xbf, 0xf8, 0xb0, 0xef, 0x59, 0x25, 0xe7,
	0x33, 0x68, 0x6b, 0xfa, 0x63, 0x3c, 0xd4, 0x5e, 0xf4, 0x26, 0x8b, 0x68, 0x3d, 0x6f, 0x8b, 0x69,
	0xfb, 0x3a, 0x80, 0xf2, 0x28, 0x9e, 0xcf, 0xb0, 0x6c, 0x31, 0x0d, 0x4f, 0xcd, 0x78, 0xe7, 0x0c,
	0xb8, 0xa2, 0xb8, 0xeb, 0x0d, 0x4f, 0x4e, 0x9c, 0xef, 0xc3, 0xa3, 0xf4, 0x20, 0x37, 0xb6, 0x48,
	0x55, 0x64, 0xc9, 0x51, 0x2a, 0x3e, 0x57, 0x11, 0x4e, 0x9d, 0x26, 0xc9, 0x74, 0xb9, 0xa1, 0x22,
	0xfb, 0xb8, 0x7c, 0x02, 0xa8, 0x3e, 0x9e, 0x1a, 0x32, 0x33, 0x86, 0xb8, 0xa7, 0x94, 0x44, 0xbc,
	0x78, 0xc9, 0x97, 0x80, 0x9a, 0x39, 0xbf, 0x33, 0xc1, 0xd6, 0x4e, 0x6d, 0xd9, 0xe2, 0xc7, 0x6b,
	0x67, 0xe5, 0xb8, 0xf7, 0x83, 0xd7, 0x0e, 0x8c, 0x37, 0x90, 0x39, 0x19, 0x11, 0x16, 0x4c, 0x7c,
	0xe1, 0x83, 0xac, 0xde, 0x0d, 0xaf, 0xa1, 0xa4, 0x42, 0x89, 0x4a, 0xd8, 0x2f, 0x49, 0xc0, 0x7c,
	0xe9, 0x92, 0xbc, 0x45, 0x55, 0x0e, 0xe3, 0xd2, 0x6b, 0x29, 0x74, 0x3e, 0xfb, 0x8f, 0x8e, 0xbf,
	0x0a, 0x25, 0xaf, 0x7f, 0xe3, 0xfd, 0xd4, 0x2a, 0x20, 0x04, 0x4d, 0x31, 0xf4, 0xaf, 0x2f, 0x4e,
	0xaf, 0xae, 0xcf, 0x2e, 0xf9, 0xf1, 0xef, 0x41, 0x4b, 0x1f, 0xbf, 0x16, 0x96, 0xde, 0xf9, 0x11,
	0xd4, 0x32, 0x0f, 0x5c, 0xfe, 0x1e, 0xba, 0xe8, 0x7f, 0x6a, 0x3d, 0xb0, 0x77, 0x3e, 0xff, 0xf2,
	0xa8, 0x70, 0x41, 0x5e, 0xf3, 0xff, 0x8e, 0xd7, 0xef, 0x9d, 0xf5, 0x7b, 0x9f, 0x58, 0x86, 0x5d,
	0xfb, 0xfc, 0xcb, 0xa3, 0x1d, 0x8f, 0x04, 0x5c, 0xa3, 0xf3, 0xb7, 0x12, 0xb4, 0x4e, 0xbb, 0xbd,
	0x73, 0x4e, 0x4a, 0x18, 0x60, 0x26, 0xff, 0x6a, 0x45, 0xf1, 0x31, 0xac, 0xbb, 0x99, 0x0f, 0xa5,
	0xdd, 0x70, 0x73, 0xbf, 0xc6, 0xc7, 0x50, 0x12, 0x7f, 0x40, 0xd4, 0x70, 0xb3, 0x7f, 0x44, 0xbb,
	0xe9, 0xe6, 0xbe, 0x88, 0xdc, 0x98, 0xe8, 0x00, 0xa9, 0x31, 0x3e, 0xcb, 0x18, 0x13, 0x8b, 0x1d,
	0xa8, 0xae, 0x3e, 0x33, 0xbb, 0xee, 0xfa, 0x2f, 0xc8, 0x46, 0xee, 0xe6, 0x9f, 0xe7, 0x5d, 0xd8,
	0xd1, 0xef, 0xf6, 0x96, 0x9b, 0xff, 0x0e, 0xd8, 0x96, 0xbb, 0xfe, 0xb4, 0x7f, 0x0c, 0x25, 0xf9,
	0xf8, 0x4c, 0xdd, 0x15, 0xd3, 0x8c, 0xbb, 0x72, 0xf9, 0x09, 0x94, 0xd5, 0xfb, 0xac, 0xe9, 0xe6,
	0x5e, 0x70, 0x76, 0xcb, 0x5d, 0x7b, 0xc0, 0x75, 0xa0, 0xba, 0x7a, 0x36, 0xec, 0xba, 0xeb, 0x4f,
	0xb2, 0x8c, 0xd3, 0x2b, 0xd8, 0xfb, 0x00, 0xd9, 0x5e, 0xed, 0x6e, 0xf4, 0x6f, 0x7b, 0xcf, 0xdd,
	0xd2, 0xd7, 0x4e, 0xa0, 0x92, 0x36, 0x17, 0xcb, 0x5d, 0xeb, 0x4d, 0xf6, 0xae, 0xbb, 0xd1, 0x81,
	0x3e, 0x80, 0x46, 0xbe, 0xe2, 0x3e, 0x74, 0xb7, 0x55, 0x68, 0xfb, 0xc0, 0xdd, 0x5e, 0xa0, 0x3f,
	0x80, 0x46, 0xbe, 0xf4, 0xa5, 0xfa, 0x39, 0x71, 0x46, 0x3f, 0x0f, 0xff, 0x18, 0x76, 0x37, 0x0b,
	0xc5, 0x23, 0xf7, 0xbe, 0x32, 0x65, 0xdb, 0xee, 0xfd, 0xf5, 0xe5, 0x39, 0xa0, 0x2d, 0xf7, 0xdb,
	0x76, 0xef, 0x2d, 0x2f, 0xf6, 0xb7, 0xff, 0xc5, 0x5d, 0xef, 0x3e, 0xf9, 0xd9, 0xdb, 0xe3, 0x90,
	0x4d, 0x16, 0x03, 0x37, 0x88, 0x67, 0x27, 0xb7, 0x21, 0x7b, 0x1d, 0xb2, 0x93, 0x20, 0xa6, 0xb3,
	0x98, 0x3e, 0xa5, 0xc3, 0x57, 0x4f, 0x27, 0x83, 0xc1, 0x88, 0x9d, 0xe0, 0x41, 0x10, 0x0e, 0xca,
	0xe2, 0xf9, 0xfc, 0xde, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0xd6, 0xfb, 0xe5, 0xb8, 0x11,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ABCIApplicationClient is the client API for ABCIApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABCIApplicationClient interface {
	Echo(ctx context.Context, in *RequestEcho, opts ...grpc.CallOption) (*ResponseEcho, error)
	Flush(ctx context.Context, in *RequestFlush, opts ...grpc.CallOption) (*ResponseFlush, error)
	Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error)
	DeliverTx(ctx context.Context, in *RequestDeliverTx, opts ...grpc.CallOption) (*ResponseDeliverTx, error)
	CheckTx(ctx context.Context, in *RequestCheckTx, opts ...grpc.CallOption) (*ResponseCheckTx, error)
	Query(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseQuery, error)
	Commit(ctx context.Context, in *RequestCommit, opts ...grpc.CallOption) (*ResponseCommit, error)
	InitChain(ctx context.Context, in *RequestInitChain, opts ...grpc.CallOption) (*ResponseInitChain, error)
	BeginBlock(ctx context.Context, in *RequestBeginBlock, opts ...grpc.CallOption) (*ResponseBeginBlock, error)
	EndBlock(ctx context.Context, in *RequestEndBlock, opts ...grpc.CallOption) (*ResponseEndBlock, error)
	ListSnapshots(ctx context.Context, in *RequestListSnapshots, opts ...grpc.CallOption) (*ResponseListSnapshots, error)
	OfferSnapshot(ctx context.Context, in *RequestOfferSnapshot, opts ...grpc.CallOption) (*ResponseOfferSnapshot, error)
	LoadSnapshotChunk(ctx context.Context, in *RequestLoadSnapshotChunk, opts ...grpc.CallOption) (*ResponseLoadSnapshotChunk, error)
	ApplySnapshotChunk(ctx context.Context, in *RequestApplySnapshotChunk, opts ...grpc.CallOption) (*ResponseApplySnapshotChunk, error)
}

type aBCIApplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewABCIApplicationClient(cc grpc.ClientConnInterface) ABCIApplicationClient {
	return &aBCIApplicationClient{cc}
}

func (c *aBCIApplicationClient) Echo(ctx context.Context, in *RequestEcho, opts ...grpc.CallOption) (*ResponseEcho, error) {
	out := new(ResponseEcho)
	err := c.cc.Invoke(ctx, "/ABCIApplication/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Flush(ctx context.Context, in *RequestFlush, opts ...grpc.CallOption) (*ResponseFlush, error) {
	out := new(ResponseFlush)
	err := c.cc.Invoke(ctx, "/ABCIApplication/Flush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error) {
	out := new(ResponseInfo)
	err := c.cc.Invoke(ctx, "/ABCIApplication/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) DeliverTx(ctx context.Context, in *RequestDeliverTx, opts ...grpc.CallOption) (*ResponseDeliverTx, error) {
	out := new(ResponseDeliverTx)
	err := c.cc.Invoke(ctx, "/ABCIApplication/DeliverTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) CheckTx(ctx context.Context, in *RequestCheckTx, opts ...grpc.CallOption) (*ResponseCheckTx, error) {
	out := new(ResponseCheckTx)
	err := c.cc.Invoke(ctx, "/ABCIApplication/CheckTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Query(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseQuery, error) {
	out := new(ResponseQuery)
	err := c.cc.Invoke(ctx, "/ABCIApplication/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Commit(ctx context.Context, in *RequestCommit, opts ...grpc.CallOption) (*ResponseCommit, error) {
	out := new(ResponseCommit)
	err := c.cc.Invoke(ctx, "/ABCIApplication/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) InitChain(ctx context.Context, in *RequestInitChain, opts ...grpc.CallOption) (*ResponseInitChain, error) {
	out := new(ResponseInitChain)
	err := c.cc.Invoke(ctx, "/ABCIApplication/InitChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) BeginBlock(ctx context.Context, in *RequestBeginBlock, opts ...grpc.CallOption) (*ResponseBeginBlock, error) {
	out := new(ResponseBeginBlock)
	err := c.cc.Invoke(ctx, "/ABCIApplication/BeginBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) EndBlock(ctx context.Context, in *RequestEndBlock, opts ...grpc.CallOption) (*ResponseEndBlock, error) {
	out := new(ResponseEndBlock)
	err := c.cc.Invoke(ctx, "/ABCIApplication/EndBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) ListSnapshots(ctx context.Context, in *RequestListSnapshots, opts ...grpc.CallOption) (*ResponseListSnapshots, error) {
	out := new(ResponseListSnapshots)
	err := c.cc.Invoke(ctx, "/ABCIApplication/ListSnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) OfferSnapshot(ctx context.Context, in *RequestOfferSnapshot, opts ...grpc.CallOption) (*ResponseOfferSnapshot, error) {
	out := new(ResponseOfferSnapshot)
	err := c.cc.Invoke(ctx, "/ABCIApplication/OfferSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) LoadSnapshotChunk(ctx context.Context, in *RequestLoadSnapshotChunk, opts ...grpc.CallOption) (*ResponseLoadSnapshotChunk, error) {
	out := new(ResponseLoadSnapshotChunk)
	err := c.cc.Invoke(ctx, "/ABCIApplication/LoadSnapshotChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) ApplySnapshotChunk(ctx context.Context, in *RequestApplySnapshotChunk, opts ...grpc.CallOption) (*ResponseApplySnapshotChunk, error) {
	out := new(ResponseApplySnapshotChunk)
	err := c.cc.Invoke(ctx, "/ABCIApplication/ApplySnapshotChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABCIApplicationServer is the server API for ABCIApplication service.
type ABCIApplicationServer interface {
	Echo(context.Context, *RequestEcho) (*ResponseEcho, error)
	Flush(context.Context, *RequestFlush) (*ResponseFlush, error)
	Info(context.Context, *RequestInfo) (*ResponseInfo, error)
	DeliverTx(context.Context, *RequestDeliverTx) (*ResponseDeliverTx, error)
	CheckTx(context.Context, *RequestCheckTx) (*ResponseCheckTx, error)
	Query(context.Context, *RequestQuery) (*ResponseQuery, error)
	Commit(context.Context, *RequestCommit) (*ResponseCommit, error)
	InitChain(context.Context, *RequestInitChain) (*ResponseInitChain, error)
	BeginBlock(context.Context, *RequestBeginBlock) (*ResponseBeginBlock, error)
	EndBlock(context.Context, *RequestEndBlock) (*ResponseEndBlock, error)
	ListSnapshots(context.Context, *RequestListSnapshots) (*ResponseListSnapshots, error)
	OfferSnapshot(context.Context, *RequestOfferSnapshot) (*ResponseOfferSnapshot, error)
	LoadSnapshotChunk(context.Context, *RequestLoadSnapshotChunk) (*ResponseLoadSnapshotChunk, error)
	ApplySnapshotChunk(context.Context, *RequestApplySnapshotChunk) (*ResponseApplySnapshotChunk, error)
}

// UnimplementedABCIApplicationServer can be embedded to have forward compatible implementations.
type UnimplementedABCIApplicationServer struct {
}

func (*UnimplementedABCIApplicationServer) Echo(ctx context.Context, req *RequestEcho) (*ResponseEcho, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedABCIApplicationServer) Flush(ctx context.Context, req *RequestFlush) (*ResponseFlush, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (*UnimplementedABCIApplicationServer) Info(ctx context.Context, req *RequestInfo) (*ResponseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedABCIApplicationServer) DeliverTx(ctx context.Context, req *RequestDeliverTx) (*ResponseDeliverTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverTx not implemented")
}
func (*UnimplementedABCIApplicationServer) CheckTx(ctx context.Context, req *RequestCheckTx) (*ResponseCheckTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTx not implemented")
}
func (*UnimplementedABCIApplicationServer) Query(ctx context.Context, req *RequestQuery) (*ResponseQuery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedABCIApplicationServer) Commit(ctx context.Context, req *RequestCommit) (*ResponseCommit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedABCIApplicationServer) InitChain(ctx context.Context, req *RequestInitChain) (*ResponseInitChain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitChain not implemented")
}
func (*UnimplementedABCIApplicationServer) BeginBlock(ctx context.Context, req *RequestBeginBlock) (*ResponseBeginBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginBlock not implemented")
}
func (*UnimplementedABCIApplicationServer) EndBlock(ctx context.Context, req *RequestEndBlock) (*ResponseEndBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndBlock not implemented")
}
func (*UnimplementedABCIApplicationServer) ListSnapshots(ctx context.Context, req *RequestListSnapshots) (*ResponseListSnapshots, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (*UnimplementedABCIApplicationServer) OfferSnapshot(ctx context.Context, req *RequestOfferSnapshot) (*ResponseOfferSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferSnapshot not implemented")
}
func (*UnimplementedABCIApplicationServer) LoadSnapshotChunk(ctx context.Context, req *RequestLoadSnapshotChunk) (*ResponseLoadSnapshotChunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSnapshotChunk not implemented")
}
func (*UnimplementedABCIApplicationServer) ApplySnapshotChunk(ctx context.Context, req *RequestApplySnapshotChunk) (*ResponseApplySnapshotChunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySnapshotChunk not implemented")
}

func RegisterABCIApplicationServer(s *grpc.Server, srv ABCIApplicationServer) {
	s.RegisterService(&_ABCIApplication_serviceDesc, srv)
}

func _ABCIApplication_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEcho)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Echo(ctx, req.(*RequestEcho))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFlush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Flush(ctx, req.(*RequestFlush))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Info(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_DeliverTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeliverTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).DeliverTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/DeliverTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).DeliverTx(ctx, req.(*RequestDeliverTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_CheckTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCheckTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).CheckTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/CheckTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).CheckTx(ctx, req.(*RequestCheckTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Query(ctx, req.(*RequestQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Commit(ctx, req.(*RequestCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_InitChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInitChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).InitChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/InitChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).InitChain(ctx, req.(*RequestInitChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_BeginBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBeginBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).BeginBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/BeginBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).BeginBlock(ctx, req.(*RequestBeginBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_EndBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEndBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).EndBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/EndBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).EndBlock(ctx, req.(*RequestEndBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestListSnapshots)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/ListSnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).ListSnapshots(ctx, req.(*RequestListSnapshots))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_OfferSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOfferSnapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).OfferSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/OfferSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).OfferSnapshot(ctx, req.(*RequestOfferSnapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_LoadSnapshotChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLoadSnapshotChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).LoadSnapshotChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/LoadSnapshotChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).LoadSnapshotChunk(ctx, req.(*RequestLoadSnapshotChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_ApplySnapshotChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestApplySnapshotChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).ApplySnapshotChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABCIApplication/ApplySnapshotChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).ApplySnapshotChunk(ctx, req.(*RequestApplySnapshotChunk))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABCIApplication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ABCIApplication",
	HandlerType: (*ABCIApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _ABCIApplication_Echo_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _ABCIApplication_Flush_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _ABCIApplication_Info_Handler,
		},
		{
			MethodName: "DeliverTx",
			Handler:    _ABCIApplication_DeliverTx_Handler,
		},
		{
			MethodName: "CheckTx",
			Handler:    _ABCIApplication_CheckTx_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ABCIApplication_Query_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _ABCIApplication_Commit_Handler,
		},
		{
			MethodName: "InitChain",
			Handler:    _ABCIApplication_InitChain_Handler,
		},
		{
			MethodName: "BeginBlock",
			Handler:    _ABCIApplication_BeginBlock_Handler,
		},
		{
			MethodName: "EndBlock",
			Handler:    _ABCIApplication_EndBlock_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _ABCIApplication_ListSnapshots_Handler,
		},
		{
			MethodName: "OfferSnapshot",
			Handler:    _ABCIApplication_OfferSnapshot_Handler,
		},
		{
			MethodName: "LoadSnapshotChunk",
			Handler:    _ABCIApplication_LoadSnapshotChunk_Handler,
		},
		{
			MethodName: "ApplySnapshotChunk",
			Handler:    _ABCIApplication_ApplySnapshotChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "abcitypes.proto",
}
